name = "PERK"
uuid = "85f1910e-5d62-11e9-1bce-2b30a05932d4"
authors = ["Steven Whitaker <stwhit@umich.edu>"]
version = "0.2.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.2"
